.gitignore, README.md, bin/nyc-report.js, bin/nyc.js, index.js, package.json, test/nyc-test.js
* pulled in @isaacs' spawn-wrap module
=> pulled in spawn-wrap module

index.js, package.json, test/nyc-test.js
I accidentally removed the standard dependency this pull re-adds it.
=> nuked standard dependency by mistake

index.js
This should improve performance somewhat
=> Break out of loop once condition has been found

package.json
Pull in bug fixes and improved HTML report design. See <https://github.com/gotwarlost/istanbul/blob/master/CHANGELOG.md>.
=> Upgrade istanbul

.gitignore
=> ignore foreground-child

test/fixtures/check-instrumented.js, test/fixtures/spawn.js, test/src/nyc-test.js
See commits. Fixes #103.
@jamestalmage
=> Do fix remaining tests

CHANGELOG.md, package.json
this should put us in a place where tap and nyc play nice again.
=> upgrade foreground-child, update changelog

bin/nyc.js
default all options to their long name, further addresses @rapzo's work here:
https://github.com/bcoe/nyc/pull/185
=> default all options to long form

README.md
=> documents indicated that configuration should be "extensions" rather than "extension"

index.js, test/src/nyc-test.js
Should have added tests in #199. My bad. I added tests here for both of the globs added in #199 and I tested it manually in my own project. Works great. Thanks!
=> fix glob pattern for exclusion and add tests

CHANGELOG.md, package.json
starting to introduce conventional-changelog to [several projects](https://github.com/yargs/yargs/blob/master/CHANGELOG.md), thanks @stevemao \o/
=> introducing conventional-changelog for changelog generation

README.md, package.json
most importantly, upgrades us to the new version of spawn-wrap with fixes for the `npm` bin.
=> feat: updating dependencies (spawn wrap with fixes)

README.md
Thanks @bcoe for `nyc` and @stevepeak for `codecov`
/cc https://github.com/codecov/codecov-node/issues/13
=> Provide codecov instructions

index.js
=> Strip any duplicate extensions from --extension

package.json
@addaleax @jamestalmage mind giving this a spin while builds run?
=> fix: upgrade foreground-child dependency

README.md
=> docs(README): Add more complete configuration example [ci skip]

test/fixtures/transpile-hook.js, test/src/nyc-test.js
=> Add unit test: addAllFiles should work correctly with non-.js files

bin/nyc.js, bin/wrap.js
=> fix: serialization using ',' was breaking globs

ISSUE_TEMPLATE
adds an issue template, to help us start collecting more actionable bug reports.
=> docs: add issue template

README.md, test/src/nyc-bin.js
added some docs and a test to @xdissent's high and low watermark work.
would love your 👀 on it @xdissent.
=> chore: add test and docs for high and low watermarks

README.md
Fixes #453 
Thanks @TonyPythoneer for pointing this out!
=> docs(readme): link to available reporters

lib/config-util.js
Replace link to deprecated repo.
Fixes #593.
=> update help link to list of reporters

README.md
https://github.com/istanbuljs/nyc/issues/613
=> Update README.md to include tap-nyc

package.json
Relate https://github.com/tapjs/spawn-wrap/commit/fc98d38664c364cc55588e39de747aef03d767ea
=> feat: upgrade the version of spawn-wrap for windows issue

package.json
explicit upgrade of istanbul-lib-instrument.
see: https://github.com/istanbuljs/nyc/issues/657
=> chore: explicit upgrade of istanbul-lib-instrument

index.js
=> fix: Do not exclude files with sourcemap from coverage

README.md
=> docs: update exclude defaults

.babelrc, README.md
https://github.com/istanbuljs/babel-plugin-istanbul/pull/138
=>  babel-preset-es2015 => babel-preset-env

README.md
update scripts property in package.json
=> docs: fix package.json script to scripts

package.json
=> chore: upgrading to newer spawn-wrap

package.json
=> fix: explicitly update spawn-wrap

package.json
update convert-source-map addressing #726.
=> chore: upgrade convert-source-map fixes #726

README.md
Hi,
Added some documentation for the custom reporter usage and installation that was introduced in https://github.com/istanbuljs/istanbuljs/pull/155
I believe this fixes/closes https://github.com/istanbuljs/nyc/issues/387
Thanks,
=> Add documentation on how to use and load custom reporters

package.json
=> chore: explicit upgrade of istanbul-reports

README.md, index.js, lib/commands/instrument.js, lib/config-util.js, package.json
@bcoe will be working on istanbuljs-website next.
=> docs: Reference babel 7 in all places

ISSUE_TEMPLATE
Ask for link to repository first, add text explaining the importance of
linking a repository that demonstrates the bug.
=> chore: Update language of ISSUE_TEMPLATE.

.github/stale.yml
From: https://github.com/probot/stale I think this is a good first pass based on the initial feedback we have! The rest of the defaults they have are reasonable IMHO but let me know if there are others that should change. I'm going to merge this soon, though, so we can just make more PRs later.
=> chore: update stale bot config with feedback

lib/commands/merge.js
=> fix: Create directory for merge destination.

index.js, test/nyc-integration.js
=> Fix unable lookup source

bin/nyc.js
Typo fixed within code comment.
=> chore: fixed minor typo

package.json
Ref https://github.com/istanbuljs/test-exclude/pull/39
=> chore: Temporarily pin test-exclude

index.js, lib/commands/instrument.js, package-lock.json, package.json, test/nyc-integration.js, test/processinfo.js
I just ran `npm run lint -- --fix`.
=> (chore): Update standard to v14.3.1

README.md
Based on https://github.com/istanbuljs/istanbuljs/pull/155
=> Mention custom reporter usage
