- bin/nyc.js
- index.js
- package.json
pulled in the signal-exit module, which ensures that an exit event is fired regardless of whether execution ends normally, via kill, or via exit.
> pulled in signal-exit module

- index.js
- package.json
* set the `alwaysLast` option for signal-exit, so that code coverage always happens last.
* upgraded signal-exit/spawn-wrap dependency.
> ensure that writing code coverage always happens last

- index.js
- package.json
upgrade of signal-exit, see:
https://github.com/bcoe/signal-exit/pull/9
we now better handle multiple listeners on a single signal.
> upgrade signal-exit

- README.md
- index.js
- package.json
- test/fixtures/.istanbul.yml
- test/nyc-test.js
Thanks for the awesome work @shackpank. I added a few tests, but otherwise things seemed to work great. a couple notes:
* Since `nyc` relies on the global coverage variable being `__coverage__` I've made this value hardcoded (in subprocesses I've seen some issues surrounding accessing `process.globals`, so I think it's good to push people towards `__coverage__`).
* I use the `this.cwd` directory variable, so that we'll keep loading the appropriate `.istanbul.yml` as `cwd` is changed in tests.
* I've added you as an owner to the GitHub project, I'm excited for any future contributions you might be able to make.
> load in instrumenter configuration from .istanbul.yml

- index.js
- package.json
upgrades signal-exit to version that better handles:
```js
process.on('exit', function () {
process.exit(5);
})
```
CC: @isaacs
> new signal-exit handles process.exit() in process.on('exit')

- .gitignore
- README.md
- bin/nyc.js
- index.js
- test/nyc-test.js
slight tweaks based on @sindresorhus' feedback: see #20 #21
* switches `nyc_output` to `.nyc_output`.
* adds note about disabling pull request comments in coveralls.
> slight tweaks based on @sindresorhus' feedback: see #20 #21

- package.json
I was going to rename it to JSONStream but it turns out that it's not being used.
Because of https://github.com/dominictarr/JSONStream/issues/68, it's causing lots of `npm ERR! missing: JSONStream@^1.0.3` and `npm ERR! extraneous: jsonstream@1.0.3 ` when your dependencies depend on both in case-insensitive OSes (e.g. browserify and tap).
> Remove unused jsonstream dep

- index.js
- test/nyc-test.js
I've added the ability to define multiple reporters at once.
Example usage from the cli:
`nyc report --reporter=html --reporter=text`
**edit**: this is just a minor convenience (over simply running the command twice), but figured it was worth a shot. ¯\\_(ツ)_/¯
> add reporter array support

- .travis.yml
- bin/nyc.js
- index.js
- package.json
* upgrade tap, which now has nyc coverage reporting/coveralls built right in.
* remove now unused coveralls dependency.
* switch reporter(s) to using the yargs `array` variable type.
> upgrade tap

- README.md
- bin/nyc.js
- index.js
- package.json
- test/nyc-test.js
Added shortcut for istanbul's check-coverage command, see #29
@Raynos, would you mind giving this branch a spin, and letting me know if this was what you're looking for?
> add shortcut for istanbul's check-coverage command

- README.md
- bin/nyc.js
- index.js
- package.json
- test/nyc-test.js
Based on @Raynos' feature request (see #29) I've combined the instrumentation and reporting steps.
I think it would be slick to show a `text` report by default, which makes this a major version bump.
@Raynos @isaacs could you give this branch a spin, the code is somewhat clever for slicing `process.argv` so I'd like to get an extra set of eyes on it.
> combine instrumentation and reporting step (it's what plants crave).

- bin/nyc.js
Looks like you're missing the [`statements` option in Istanbul](https://github.com/gotwarlost/istanbul/blob/f556b46aef4963820c9239fd217f6f08ace275b7/lib/command/check-coverage.js#L62-L65).
> add statements checking to code-coverage

- bin/nyc.js
- package.json
@rmg pointed out in this pull request #30 that istanbul was being invoked in a manner that would work poorly if istanbul got hoisted up into a higher folder.
I've switched to using an approach which @othiym23 and @iarna suggested today:
1. I aded istanbul to npm run scripts.
2. I muck with the `cwd`, so that I can invoke the npm run script from the context of nyc.
3. I invoke the npm run script.
@jasisk I also added the `statements` option in this pull we didn't actually collide on the `s` key, because `s` was used on the outer `yargs` chain, not the inner `yargs` chain.
Let me know what ya'll think.
> spawn istanbul in such a way that works for npm@3.x

- bin/nyc.js
- index.js
- package.json
- test/nyc-test.js
This doesn't fix the problem of coverage not working on Windows, and it isn't a complete fix to the general problem of running on Windows, but if tap is upgraded to a version of nyc with this fix applied it should at least stop crashing on Windows when `tap --coverage` is run.
It may even fix #26 
/cc @sam-github @isaacs
> Fix windows spawn

- index.js
First of, thanks for adding source map support! I've been trying to use `nyc@4` with the [project](https://github.com/novemberborn/buoyant) that lead to my [code coverage article](https://medium.com/@novemberborn/code-coverage-with-babel-istanbul-nyc-83b8c2f1093#.29ern9dza) from last week. I got it working but had to make some changes. This is the first PR which covers the custom require hook implementation.
---
The custom hook should decide which modules it wants to ignore. For example Babel lets you customize this beyond just `node_modules` using the [`only` and `ignore` options](https://babeljs.io/docs/usage/options/).
Custom hooks often store the hook they're replacing, and may call this hook when loading a module (e.g. if they decide to ignore that particular module). Hooks may also …
> Improve support for custom require hooks

- package.json
An HTML report may be generated during development. This report contains JS files that should not be instrumented when running the test suite.
> exclude coverage folder when instrumenting

- index.js
- lib/source-map-cache.js
First of, thanks for adding source map support! I've been trying to use `nyc@4` with the [project](https://github.com/novemberborn/buoyant) that lead to my [code coverage article](https://medium.com/@novemberborn/code-coverage-with-babel-istanbul-nyc-83b8c2f1093#.29ern9dza) from last week. I got it working but had to make some changes. This is the second PR which covers the source map handling.
---
I'm now caching a source map if a file is added, even if the dependency wasn't loaded via a custom require hook. This helps with cases where the file was compiled using say a watcher.
nyc now also loads source maps that are merely referenced by the source file.
Finally, if the covered file came from a single source (according to its source map), the `path` is rewritten to the original source. …
> Improve source maps

- index.js
- test/source-map-cache.js
combining #73 and #66 broke tests on master:
* since #66 rewrites paths based on the source-map, the paths being used to lookup coverage info in tests were broken.
* removing babel from `nyc` in #73 identified an issue with `require.main.paths()` I've instead moved to an approach that: 1. attempts requiring from the current working directory 2. falls back to requiring the full path of the additional module.
CC: @Lalem001, @novemberborn
> the combination of #73 and #66 broke tests on master

- package.json
- test/fixtures/_generateCoverage.js
- test/fixtures/coverage.js
- test/source-map-cache.js
Tests `_rewritePath()` as requested by @bcoe in #66.
I'd like to add a test for reading a source map file but I'm not quite sure where to put it. I mean I can test the `add()` method I suppose but there's no real test even verifying it's called. @bcoe any ideas? Happy with the coverage we have now?
---
This bumps `source-map-fixtures`. I've added a `sourceFile` path which can be used to create the `mappedPath` from #76.
I realized the generated coverage report already applied source maps. It now writes the raw coverage file instead.
I've added a few more fixtures (with coverage) to test `_rewritePath()`.
> Add source map tests

- CHANGELOG.md
- README.md
- index.js
- package.json
- test/fixtures/package.json
- test/nyc-test.js
A few slight tweaks to Lalem001's awesome work on glob-based excludes:
* I've switched to (at this time an older) version of `micromatch`. This works with leading `./` so that using `npm link` does not break exclusions.
* I've added support for `include` along with `exclude`.
Reviewers: @Lalem001, @davidchase, @novemberborn
> glob-based include/exclude functionality

- package.json
The intent was to use an older version of micromatch, but the current
semver specification allows up to latest.
The carrot range will allow any version up to, but not including 3.0.0.
Switched to a tilde range which allows up to, but not including 2.2.0.
> use a tilde range for micromatch

- CHANGELOG.md
- node_modules/spawn-wrap/index.js
nyc works with subprocesses on my virtualbox testing image now:
we still need to do some work to get the `nyc` tests themselves passing -- and I dream of one day getting back on the `latest` version of spawn-wrap so that we can stop bundling dependencies ... but, one step at a time.
> patch to make cmd shim work in subprocesses on windows

- index.js
- package.json
Well this was easy!
This is #89, with with one commit from cherry picked from #77 (unmodified, not even a conflict!).
If nothing else, it's confirmation our testing strategy is moving in the right direction.
Now that I have `capture-require` actually working with something beyond it's own test suite, I guess it is time to publish it for real.
> Recast forking with capture require

- lib/source-map-cache.js
- package.json
- test/fixtures/_generateCoverage.js
- test/fixtures/coverage.js
- test/src/source-map-cache.js
remap-istanbul's mapping function seems to cover more edge cases, as well as preserving "skip" annotations. This commit rewrites nyc's mapping logic to use a helper function adapted from remap-istanbul. See <https://github.com/SitePen/remap-istanbul/blob/30b67ad3f24ba7e0da8b8888d5a7c3c8480d48b2/lib/remap.js#L55:L108>
for the original.
Fixes #67.
@bcoe `remap-istanbul` is [BSD licensed](https://github.com/SitePen/remap-istanbul/blob/30b67ad3f24ba7e0da8b8888d5a7c3c8480d48b2/LICENSE). Not quite sure what attribution is required in the source code for copying their function.
It's possible that including the ["skip" annotation](https://github.com/SitePen/remap-istanbul/blob/30b67ad3f24ba7e0da8b8888d5a7c3c8480d48b2/lib/remap.js#L105) in nyc's existing logic is sufficient. Here's where I have to …
> adapt remap-istanbul's mapping logic for nyc

- index.js
- package.json
We had two problems. 
1. Our attempt to resolve the module passed to the `--require` 
flag was grabbing from `nyc/node_modules. A switch to `require-from` solved that.
2. We were collecting source-map information from every file required. This
caused bad things to happen when convert-source-map saw it's source-map-comment
regular expression and thought it was an actual source map comment. Only
collecting source map information when needed made things run faster and 
fixed the problem
> Fix ability to self-test using `npm link`.

- test/src/nyc-test.js
> module._compile() correctly expects a second filename argument

- README.md
- appveyor.yml
- package.json
- test/fixtures/child-1.js
- test/fixtures/child-2.js
- test/fixtures/spawn.js
- test/src/nyc-test.js
- test/src/source-map-cache.js
This wasn't as much work as I'd feared, fixes #81 \o/
Here's a break down of the changes I've made:
* I've added the `appveyor.yml` that @sindresorhus recommended.
* I switched to using `rimraf` for deleting left over test data, since it's cross-platform.
* windows doesn't (or at least `signal-exit` on Windows) doesn't support `process.kill()`, I've disabled the two tests that require `process.kill` using the `is-windows` module.
* I've also made the spawn tests not rely on scripts that call `process.kill`.
* I was running into issues with `path.sep` being `\` on Windows and `/` on *nix. 
* `nyc` and `Istanbul` have paths that are all over the place on Windows (sometimes using one separator, sometimes another).
* rather than try to unravel this mess (since it doesn't break anything but …
> get tests passing on Windows

- docs/profiling.md
This adds a `maintaining.md` file where we can store information helpful to maintainers.
The first entry is a set of instructions for self-profiling, based on my comments [here](https://github.com/bcoe/nyc/pull/101#issuecomment-165337057).
> add profiling instructions

- bin/nyc.js
- index.js
- test/src/nyc-test.js
This adds a `reset` method which deletes the temp directory then adds it back. `createTempDirectory` is no longer called for every forked process.
Instead of writing a test for  #120, I just went ahead and fixed #112. I have verified it would have caught the error.
Fixes #120 
Fixes #112
> Add reset, clean up before every test

- index.js
- package.json
Uses `find-cache-dir` for consistent cache locating with other modules (currently that list only includes AVA, but one can hope). It takes the extra step of ensuring a `package.json` file exists (and hunting up the directory tree for it), otherwise it returns null. If it can't find a suitable cache directory, caching is disabled.
I also dropped the `cacheDirectory()` method in favor of just setting a property.
> Use find-cache-dir to determine cache directory.

- bin/nyc.js
- index.js
- package.json
- test/fixtures/cache-collision-runner.js
- test/src/nyc-test.js
> merge #123 with master (upgrade foreground-child, spawn-wrap).

- bin/nyc.js
fixes #105, this pull adds a shorthand for checking coverage thresholds. You can now do the following:
`nyc --check-coverage --lines=100 tap test/*.js`
reviewer: @isaacs
> add --check-coverage shorthand, which fails tests if coverage slips below threshold

- README.md
- index.js
- package.json
- test/src/nyc-test.js
Fixes #131
This also uses `pkg-up` to locate the nearest `package.json` from `cwd`, and will move `cwd` to there. This allows you to invoke `nyc` from a subdirectory of your project and still have it behave as expected.  This is something our caching mechanism already does. If it can't find a `package.json`, it just uses the original `cwd` option.
> Use `nyc` instead of `config.nyc` in package.json

- README.md
I've updated documentation based on the discussion in #134. @jamestalmage, @tcurdt, could you give this a read?
fixes #134
> updated documentation based on the discussion in #134

- bin/nyc.js
- bin/wrap.js
This makes it possible to self-test node-tap's coverage reporting and
coverage level checking when running in covered mode.  Otherwise, doing
`node {nycBin} check-coverage` results in executing the nyc executable
script as the main file (or worse, some module named `check-coverage`,
which obviously doesn't exist).
> Don't try to cover the bin/nyc.js file

- bin/nyc.js
- index.js
- package.json
- test/src/nyc-test.js
fixes #63 
reviewers: @jbcpollak, @mateatslc, @jamestalmage
> allow the directory that coverage reports are outputted to to be configured

- .gitignore
- bin/nyc.js
- index.js
- test/fixtures/transpile-hook.js
- test/src/nyc-test.js
@jwhitfieldseed could you give this branch a shot and let me know if it does the trick for you?
Reviewers: @jamestalmage @novemberborn
> we should still run transpilers on source files included via --all

- lib/source-map-cache.js
- test/src/source-map-cache.js
Istanbul can sometimes return illegal position values. Clamp them so they can be used by the source map consumer.
See https://github.com/bcoe/nyc/pull/143#issuecomment-173554681 for background.
> guard against illegal positions

- lib/source-map-cache.js
- package.json
- test/fixtures/_generateReport.js
- test/fixtures/report.js
- test/src/source-map-cache.js
Istanbul may mark functions as being skipped. Make sure these annotations are preserved when source maps are applied. Fixes #67.
> Preserve function skip annotations

- index.js
- test/src/nyc-test.js
Files outside of the current working directory (meaning higher up in the file hierarchy) should not be instrumented.
Fixes #157 where nyc is run from inside a `node_modules` directory.
Fixes #154 where 'npm link' is used to fulfil dependencies.
This removes matching the include/exclude patterns to the absolute filename, the patterns are now applied only to the relative portion within the current working directory.
`addAllFiles()` has been changed to explicitly add files in the current working directory only.
Some other tests related to include/exclude behavior have been cleaned up.
---
Note that I'm not entirely certain `filename` in `shouldInstrumentFile()` is always absolute. Review on that front would be especially appreciated.
This changes the include/exclude matching behavior, but …
> Don't instrument files outside of the current working directory

- index.js
- lib/source-map-cache.js
- test/fixtures/_generateReport.js
- test/fixtures/report.js
- test/src/nyc-test.js
- test/src/source-map-cache.js
Pass an absolute path to the instrumenter. This results in the coverage containing absolute paths.
Adjust caching and source map logic to use absolute paths. Rename variables.
The change to the source map logic should let it handle source map sources that have absolute paths. Before these were joined to the file path, now the new path is resolved instead.
Fixes #110.
> Use absolute file paths in coverage

- README.md
- bin/nyc.js
- bin/wrap.js
- index.js
- package.json
- test/fixtures/check-instrumented.es6
- test/fixtures/check-instrumented.foo.bar
- test/fixtures/package.json
- test/src/nyc-test.js
This adds support for allowing files with extensions other than '.js' to be covered.  It can be configured through package.json config, or command line args.  
As per my comment in issue https://github.com/bcoe/nyc/issues/161#issuecomment-180747165, there aren't any additional tests yet. If you feel some additional tests to cover this functionality would be helpful, I'd appreciate some guidance as to how you think they could be done (I'm not quite used to the way the existing tests are done).  Even just pointing me to existing tests that I could pattern after, would be great.
I'd be glad to address any other comments also.
> Add support for configurable file extensions

- README.md
- bin/nyc.js
- index.js
- package.json
- test/fixtures/package.json
- test/src/nyc-test.js
This will need to be a major bump, because I've retired `config.nyc`.
This upgrades us to `yargs 4.x` which is a pretty major change (so that I can use the new `pkgConf` feature), this is a pretty major change and I would love for folks to take an extra close look to make sure I haven't broken anything.
Note that I could delete a bunch of code with yargs' improved command functionality \o/
Reviewers: @novemberborn, @jamestalmage, @jameswomack, @lloydcotten
> all of nyc's configuration options can now also be set in package.json

- .editorconfig
- README.md
Note: introducing these changes raises a question in the coveralls
example at the bottom: does `nyc` really need to be run again for the
report to be available? and wouldn’t it be better just to have the lcov
report generated alongside the regular text display, and have the
`after_success` command just `cat` and pipe it to `coveralls`?
> Add an EditorConfig and clean up readme

- index.js
- package.json
The library `pkgUp` is used to find the closest package.json, which nyc uses as `cwd`.
If `pkgUp` walks all the way to `/`, it returns the string `package.json`. In this edge-case, we should not switch to `cwd` to the path of the package.json found by `pkgUp`.
> do not infer cwd from pkgUp, if pkgUp walks all the way to /

- bin/nyc.js
As pointed in [issue #184](https://github.com/bcoe/nyc/issues/184).
> Removed yargs default for reporters so the ones defined in  are taken first

- index.js
- test/src/nyc-test.js
I personally use (and teach) that applications should co-locate test files and source code, which is where the `*.test.js` comes from.
The React community uses the `__tests__` convention.
Happy to make any changes you'd like to see :-)
> add more exclude glob patterns

- bin/nyc.js
Resolve the issue mentioned in #209 that, when running with `--check-coverage`, the coverage check’s exit code overrides the test command’s. This depends on tapjs/foreground-child#7 in order to work (without it, the current behaviour is simply retained).
> Use test program’s exit code even with `--check-coverage`

- bin/nyc.js
- bin/wrap.js
- index.js
- test/fixtures/cli/test.js
- test/fixtures/conf-empty/package.json
- test/src/nyc-bin.js
- test/src/nyc-test.js
> Add `include` to CLI options

- lib/source-map-cache.js
Spotted positions like these in coverage output when debugging #239:
```json
"1": {
"start": {
"line": 1,
"column": 0
},
"end": {
"line": null,
"column": -1
}
},
```
This PR adds a guard against badly adjusted end positions, causing those locations to drop out of the report.
> Discard more bad source map positions

- appveyor.yml
Only test against stable and LTS versions of node since AppVeyor goes pretty slow.
@bcoe I noticed that after dropping the Travis build times to 1/4th of what they were on Travis in #251, AppVeyor's build takes even longer... so this is an attempt to streamline it by using the version of `npm` that comes with each node distro and only going for stable and LTS versions. Thoughts?
> Update AppVeyor config with ~faster npm install

- README.md
- bin/nyc.js
- test/src/nyc-bin.js
it felt a little weird providing a noop instrumenter directly in `__coverage__`, this pull introduces the `instrument` flag instead -- making it possible to setup `__coverage__` with the following config:
```json
"nyc": {
"include": [
"index.js"
],
"require": [
"babel-register"
],
"reporter": [
"lcov",
"text"
],
"sourceMap": false,
"instrument": false
}
```
which feels cleaner.
> feat: add "instrument" option as alternative to specifying noop instrumenter

- README.md
I updated the docs, so that it prevents the `__coverage__` plugin from kicking in in development/production mode.
> Docs: Only enable __coverage__ plugin in test env.

- README.md
> docs(env): Add reference to cross-env

- index.js
With AVA's concurrency flag, it's possible that two processes during a test run will share the same pid.
Avoid this collision by hashing the pid with process.hrtime for a truly unique value.
> Avoid pid collisions.

- README.md
- bin/nyc.js
- package.json
the interactions between the ava, babel, and nyc cache were causing a lot of confusion for folks, see:
https://github.com/istanbuljs/nyc/issues/296
https://github.com/istanbuljs/nyc/issues/294
In this pull request:
* we leave nyc's cache as opt in (I was considering making it run by default in 7.x).
* we disable babel's cache when running tests with nyc (this cache caused a lot of issues with babel-plugin-istanbul).
> fix: disable the babel/nyc cache

- bin/nyc.js
- index.js
- lib/process-args.js
- package.json
- test/fixtures/cli/args.js
- test/src/nyc-bin.js
- test/src/nyc-test.js
- test/src/process-args.js
This pull request is an attempt to make nyc's argument parsing more clever, in the past:
`nyc npm test --silent`
would have resulted in `nyc` itself reading the `--silent` flag, and failing to print output.
With this fix, nyc instead parses:
`nyc npm test`, dropping the trailing arguments.
fixes: #99, #201 
Reviewers: @MoOx, @jamestalmage, @danez, @JaKXz
> feat: nyc no longer tries to run arguments passed to the instrumented bin

- index.js
I'm using TypeScript for a project, and when I run nyc with the *--all* flag, I keep getting errors such as:
*failed to instrument /microservices/ms-gateway/app/entities/UserEndpoint.ts with error: 'import' and 'export' may appear only with 'sourceType: module' (1:0)*
My package.json config looks like this:
```json
"nyc": {
"include": [
"app/*.ts",
"app/**/*.ts"
],
"extension": [
".ts"
],
"require": [
"ts-node/register"
]
}
```
It happens because under the hood, the code was trying to instrument the TypeScript code rather than the transpiled JavaScript code.
> Make --all flag work with files with extensions other than .js

- index.js
A simple fix that forces the provided absolute path to use `this.cwd` instead. This is a windows only fix, so let me know if it should be wrapped in a `if` statement for platform checks.
> Handles correct path casing. Fixes #269.

- index.js
- test/fixtures/cli/subdir/.gitignore
- test/fixtures/cli/subdir/input-dir/index.js
- test/src/nyc-bin.js
Hi everyone! Ran into a problem running `nyc instrument` today, and it would be cool if you could take a look at. I’m pretty sure this is a correct fix, but still, removing code always comes with the suspicion that there is a reason it was there in the first place. ;)
------
There is no real reason to use a relative path when performing the I/O for instrumenting. Absolute paths should work just as well and will be correct, even when `nyc.cwd` is off a bit because it is modified based on what `pkgUp` says.
> Make `nyc instrument` work in subdirectories

- bin/nyc.js
- package.json
- test/src/nyc-test.js
BREAKING CHANGE: node_modules is no longer automatically excluded, and an empty array of exclude rules can be provided.
> feat: upgrade to new test-exclude; with suppport for node_modules

- lib/process-args.js
- test/fixtures/cli/gc.js
- test/src/nyc-bin.js
- test/src/process-args.js
Assume that commands starting with `-`, e.g. `--expose-gc script.js`, implicitly are Node.js commands.
Fixes: https://github.com/istanbuljs/nyc/issues/337
While on the one hand I’m not sure if this isn’t handled better on `tap`’s side, I *think* this makes sense anyway.
> Implicitly assume `node` when the command starts with an option

- README.md
via [v8.0.0](https://github.com/istanbuljs/nyc/blob/master/CHANGELOG.md#800-2016-08-12)
Please let me know if I understood this correctly :)
And if you don’t mind me asking here, for a setup like this one:
https://github.com/hoodiehq/spawn-pouchdb-server/blob/master/package.json#L6
Should I know exclude `node_modules`?
> docs(README): `node_modules` is no longer excluded

- README.md
`babel-core/register` is deprecated (and other samples in the readme uses `babel-register`)
> Use `babel-register` in readme

- index.js
- Deduplicate merging of all coverage files
- Use the `map.getCoverageSummary()` convenience method
- Use convenience getters of `CoverageSummary` objects
I realize `_getCoverageMapFromAllCoverageFiles` is quite an expressive name, but then again I like expressive names.
> cleanup: simplify istanbul-lib-coverage API usage

- README.md
- bin/nyc.js
- bin/wrap.js
- build-self-coverage.js
- index.js
- lib/process.js
- package.json
- test/fixtures/cli/selfspawn-fibonacci.js
- test/src/nyc-bin.js
Add a `--show-process-tree` that shows a pretty tree of all spawned processes after `nyc` has run.
The data files for that are stored in `processinfo` are stored in `(temp directory)/processinfo` so that they don’t interfere with the fixed format of the coverage files.
Fixes: https://github.com/istanbuljs/nyc/issues/158
Right now this only displays the commands as they are being run, ex:
```
$ nyc --show-process-tree npm run pretest
> nyc@8.1.0 pretest /home/sqrt/src/nyc
> standard
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                | …
```
> feat: gather process tree information

- index.js
- test/src/nyc-bin.js
> fix: add shim for check-coverage on node 0.10

- index.js
when we make potentially breaking changes to the cache, e.g.,
https://github.com/istanbuljs/istanbul-lib-instrument/pull/22
we should increment the cache version, forcing an invalidation so that folks don't see issues like #392
> fix: add a feature which allows us to bust the cache when breaking changes are introduced

- lib/config-util.js
Support for a .nycrc config file has been added.
> chore: Remove 'coming soon' note for .nycrc file

- package.json
find-up@2 is not compatible with Node.js 0.10, which is our oldest supported Node.js version.
Follow-up to <https://github.com/istanbuljs/nyc/pull/399#issuecomment-248361632>.
> chore: tell Greenkeeper to ignore find-up releases

- package.json
> mind submitting the corresponding pull to nyc; I think that's the only other place we need to update?
@bcoe I assume you referred to a dependency bump?
> Istanbul-lib-source-maps 1.0.2

- index.js
- lib/process.js
- test/src/nyc-bin.js
- test/src/nyc-test.js
Show line coverage for each subtree of the tree of spawned processes.
This is just a start, but while I definitely wanted to begin working in that direction as planned, I’m not too certain about how this is best implemented when it comes to visual display… In theory, a full per-file coverage table could be shown for each subtree, but that seems like overkill, so I’ve just implemented something small. Also, maybe printing this extra information should be optional/configurable, too?
What do you think?
> feat: implement coverage details for process tree

- index.js
- lib/instrumenters/noop.js
- package.json
This is part of my fix for using `--all` on externally instrumented files, as when using babel-plugin-istanbul (https://github.com/istanbuljs/babel-plugin-istanbul/issues/4). I laid out the idea for this part [here](https://github.com/istanbuljs/istanbul-lib-instrument/pull/28#issuecomment-254422567).
Requires istanbuljs/istanbul-lib-instrument#28 and babel/babel#4746 (update: now both released, in istanbul-lib-instrument v1.2.0 and Babel v6.18.0 respectively).
To see the results and/or test this yourself, see the repo I've put up at https://github.com/motiz88/nyc-all-demo.
Known problems/kludges:
* The code makes a special case in `_maybeInstrumentSource` for `!this.instrument && this.all`, in which case it will always go on to "instrument" the file (actually read the existing data in …
> Read initial data from pre-instrumented files in "noop" instrumenter

- README.md
- index.js
- lib/config-util.js
- lib/instrumenters/istanbul.js
- package.json
- test/fixtures/stack-trace.js
- test/src/nyc-test.js
@kpdecker I had some refactoring on my mind, that I opted to tack onto your work so that we can get this landed -- rather than overly marking up #393.
I made a few very minor changes:
* I think that source-map production and the application of source maps, are different enough behavior that it's worth introducing the additional flag `--produce-source-map`; I also had some performance concerns, and think it's better that folks using `source-map-support` opt in.
* I've been trying to gradually pull more and more logic out of `index.js`, so that it's ultimately just calling a bunch of pretty easy to follow libraries and helpers. tldr; I pulled the source-map logic into the instrumenter.
* I added a couple `TODOs` around adding additional tests, and opened #438.
CC: @JaKXz would love to have …
> feat: adds support for source-map production

- index.js
- test/src/nyc-bin.js
This is an advanced workaround I've put in place for some experiments with the npm CLI; I'm opting to not document the flag for the time being, as I'd like to keep the help terse.
> feat: allow an alternate cache folder to be provided

- package.json
new spawn-wrap should address @TheAlphaNerd's issues with CITGM, and pulls in @wyze's fix for function names in istanbul-lib-instrument.
> fix: upgrade spawn-wrap and istanbul-lib-instrument

- bin/nyc.js
Specifically, if the temp directory is configured, this needs to be configured on the NYC instance for both the command line action `check-coverage` as well as the `--check-coverage` flag passed when executing tests.
> Fix check-coverage with custom options

- index.js
Passes watermarks from the nyc config to `istanbul-lib-report`. This should allow custom watermarks for all reporters in `istanbul-reports` that use them. In the old `.istanbul.yml` the watermarks lived under a `reporting` key, so maybe this should be there too, but I read thru some of the other PRs about the new config and thought this might make more sense in the context of those discussions. Plus `reportDir` was already top level too.
> feat: reporting watermarks

- index.js
- lib/config-util.js
This change adds an `--eager` option to nyc which forces instantiation
of the instrumentation library prior to walking any of the files.
Addresses #491
> Allow eager instantiation of instrumenter

- lib/instrumenters/noop.js
This allows the use of `--all` with `babel-transform-istanbul`, for instance.
> Fix use of --all when instrumentation is disabled

- bin/nyc.js
- lib/config-util.js
Allow the babel cache to be disabled, thanks for the patch @Arturszott.
In this pull I make one tiny tweak, the environment variable is now simply not set if you set `babel-cache=true`.
> feat: allow babel cache to be enabled

- README.md
Depends on https://github.com/istanbuljs/istanbuljs.github.io/pull/37
I did this for the sake of paring down the README to a _simpler_ quick start because I'm finding myself answering the same questions in our issues multiple times. This is just a step towards that end, and a further iteration will see the README better organized somehow [very open to suggestions on this].
> docs(readme): move advanced features to docs site

- .travis.yml
node@6 is the current LTS. "stable" is node@7
Might want to consider dropping 0.10, 0.12 and 5 as they are EOL, but as a testing tool, maybe not? 😄
> Test node 6 on travis

- bin/nyc.js
- lib/config-util.js
- package.json
This pull request is a follow on to #556, which starts to switch some of our non-integration tests over to mocha (it was driving me bonkers not having --grep functionality in our slow suites).
@addaleax since nyc's own test suite now requires merging multiple test runs into a single coverage report, I revisited https://github.com/istanbuljs/nyc/issues/515
The approach now outputs both the tap integration tests, and the mocha tests to the same temporary folder, and runs report once all tests have run.
Once this is landed, can we close out #515?
> feat: add support for --no-clean, to disable deleting raw coverage output

- index.js
- lib/source-maps.js
> fix: introduced a bug that resulted in source-maps not being loaded properly on second run

- index.js
- package.json
- test/nyc-bin.js
- test/nyc.js
fixes #563, don't create a `.cache` folder if `--cache=false`.
> fix: we should not create a cache folder if cache is false

- .travis.yml
- appveyor.yml
- lib/config-util.js
- package.json
Addresses #579 by updating `find-up`. Tests pass after the update, which allows for an array of filenames to be passed into `sync`. AFAICT there are no breaking changes in the way `findUp` is being used – `sync` will accept a string or an array, and there are only two calls to `findUp.sync` that I can find in the codebase.
I looked into making a test for this, and I'm happy to take a crack at it, but it seemed like duplicating a lot of stuff (fixtures, setup, etc) for little gain.
Honestly, I don't really know how important or useful this PR is, but it does seem like other similar tools I use (ESLint, e.g.) allow for file extensions on their rc files, and it is minutely helpful to my own development workflow.
> Allow .nycrc.json

- README.md
- package.json
this introduces the slick new feature of `extends`, which will allow folks to publish preset configurations for nyc; see https://github.com/istanbuljs/istanbuljs/tree/master/packages/nyc-config-babel
> feat: upgrade to version of yargs with extends support

- package.json
see: https://github.com/istanbuljs/nyc/issues/599
> fix: upgrade to spawn-wrap version that works with babel-register

- README.md
- bin/nyc.js
- index.js
- lib/config-util.js
- test/nyc-bin.js
> added support for per file coverage checking

- index.js
As dicussed in https://github.com/istanbuljs/istanbuljs/pull/24
I found some time to recreate the implementation of this using sourcemaps. The sourcemaps made it way easier and it looks nicer as well now!
To reiterate why I made this: I've a 'non-standard' setup, where I build my distribution-packages outside of the source folder. I do this because I write mainly ES6 code, and distribution-packages need to be plain old JavaScript. In addition because AVA is perfectly able to run ES6 tests, but not able to test ES6 modules I've to transpile my ES6 code (using rollup and babel/bublé) to plain JavaScript. The resulting transpiled file will also include all libraries being imported.
In addition you can use this feature to make more specific reports. Instrument once, and split your reporting …
> Add possibility to filter coveragemaps

- index.js
Fixes #581 by scrubbing the coverage object to remove any excluded files for which coverage was generated.
I'll admit to not being entirely sure how the coverage gets in for those files in the first place (the exclude logic appears to be running correctly in `addAllFiles()`), but this provides a catch-all at the end of processing to clean it up.
There's also a question about whether the scrub should occur before or after following source maps. Doing it before seems to make the most sense based on how things work now.
> Remove excluded files from coverage before writing

- lib/config-util.js
- test/src/nyc-tap.js
I added support for --root option
I found out that the `cwd` option does exactly what the --root is supposed to do except:
- the NYC_CWD environment has no documentation
- the implicit lookup for upward package.json is not something I would expect
So I added a --root option that simply force cwd to be what I tell it to be.
> Add support for --cwd (#542)

- bin/nyc.js
this change ensures the temp dir always exists, even if you use `--no-clean`.
> always create temp dir; closes #663

- .npmrc
This prevents package-lock.json from being created locally. It's already gitignored, but local devs won't have an accurate experience when the lockfile exists.
This fixes that.
> Only apps should have lockfiles

- lib/commands/instrument.js
If invoked with `nyc instrument` it wasn's possible to attach the sourcemap. This created problems for me in the coverage reports created.
> Create sourcemap in instrumented files

- package.json
This patch upgrades nyc to spawn-wrap v1.4.0 to allow for setting a custom base path for the spawn-wrap temporary directory. This allows for more customization in the location of files created on disk, to allow for running coverage in environments where write access to the file system is limited.
I'm not actually sure why this change is required. In the nyc `package.json` file, the version is set to `^1.3.8`, which I thought would allow 1.4.0 to install. However, when i set `"nyc": "^11.2.1"` in my devDependencies, and do `npm i && npm ls spawn-wrap` from a clean slate with no `package-lock.json`, I get
```
└─┬ nyc@11.2.1
└── spawn-wrap@1.3.8
```
I'm running node v8.7.0 and npm v5.4.2
> Update spawn-wrap to 1.4.0

- bin/nyc.js
- lib/commands/check-coverage.js
- lib/commands/instrument.js
- lib/commands/report.js
- lib/config-util.js
- package.json
- test/src/nyc-tap.js
* upgrading to fancy pants new yargs API; as usual nyc gets to be the guinea pig.
* refactoring the config helper a bit in the process; it was starting to look pretty crufty.
> chore: upgrade to yargs 10

- index.js
- lib/config-util.js
- package.json
fix issue [#85](https://github.com/istanbuljs/istanbuljs/issues/85) along with [this pull request](https://github.com/istanbuljs/istanbuljs/pull/90) to istanbuljs. The CI check on this pull request will fail because of dependency on the other pull request.
> hook vm.runInContext

- README.md
In the sample code, `check-coverage` was being shown as a flag (with dashes) rather than a straight up command.
> Correct examples in README.md

- index.js
- lib/commands/instrument.js
- test/nyc-bin.js
@bcoe As #697 fixed the source-map issues I was looking to fix in #696, this PR only contains the other minor fixes included in that PR.
Specifically:
- Added a test to prove sub-directories can be instrumented
- Added a missing callback call and exit code to ensure all tests still pass
> Instrumenter test and callback

- README.md
The example does not correctly show the shorthand usage, this PR corrects that.
> docs: correct check-coverage shorthand example

- .gitignore
- bin/nyc.js
- lib/config-util.js
- lib/process-args.js
- test/fixtures/cli/nycrc/.nycrc-config.json
- test/nyc-bin.js
- test/process-args.js
This PR allows us to specify a different path for `.nycrc`.
> NOTE: Some projects need different settings for _backend_ and _frontend_ tests. I'm working on a project that we do need different settings for both _backend_ and _frontend_ tests.
> Also [mocha](https://mochajs.org/) allows us to do it as well, by providing the argument `--opts`.
Thanks for understanding.
> Add a new argument to specify a different path for nycrc

- index.js
- lib/commands/instrument.js
- lib/config-util.js
- lib/instrumenters/istanbul.js
- there is no noCompact option in istanbul, only a compact option. fixed its usage
- add --[no-]compact and --[no-]preserve-comments and pass them on to
istanbul
I wasn't 100% sure what the default for preserveComments should be. Reading the code, it seemed to me that the intention was to have comments stripped by default but the current behaviour is to not strip comments, so I stuck with the current behaviour in order to keep the users' setups the same.
Please note that due to a bug in istanbul-lib-instrument, the preserveComments option set to false doesn't do anything yet. I filed another pull request with a fix for that as well: https://github.com/istanbuljs/istanbuljs/pull/122
I hope the changes are OK, please let me know if not :-)
> add command line options to control compacting and comment removal

- index.js
when invoked with `nyc --cwd sub-directory`, coverage reports were saved in `./coverage`, shouldn't it be `./sub-directory/coverage`?
> coverage reportDir should respect `--cwd`

- package.json
Originally this was added in #402 but find-up has since been updated
> chore: remove greenkeeper ignore for find-up

- package.json
The dependency is not used, so removing it from package.json.
> Removes split-lines dependency.

- package.json
Pulled in the new version of yargs that allows extending `rc` files so consumers of this module can extend `.nycrc`.
> bump yargs version for extending configs

- index.js
- lib/process.js
Fix for https://github.com/istanbuljs/nyc/issues/805
> load coverage files individually instead of all at once

- README.md
I've added a reference to the NPM package `minimatch` that is used internally by the NPM package `test-exclude`, to provide developers with a guide to the allowed matching features.
I've also described how internally more patterns are added depending on the provided patterns.
That said, I think [this regexp](https://github.com/istanbuljs/istanbuljs/blob/master/packages/test-exclude/index.js#L114) is wrong, since it only adds `file.js` when `**/file.js` provided. If I provide `./lib/**/*.js`, it doesn't add `./lib/*.js` automatically.
This regexp could be changed to `/\*\*/g`, assuming the developer only uses the double asterisks once inside the pattern, so it only expands (adds the new pattern) if the pattern (or the last path token) is a name without special matching characters. Any …
> docs: reference minimatch usage and explain pattern expansions

- index.js
- lib/commands/instrument.js
- test/fixtures/cli/subdir/input-dir/bad.js
- test/nyc-bin.js
the fact that we didn't exit on instrumentation errors lead to confusing behavior on the Node.js project, see:
https://github.com/nodejs/node/issues/20952
> feat: add option that allows instrument to exit on error

- index.js
- lib/config-util.js
- test/fixtures/cli/skip-full.js
- test/nyc-bin.js
@chrismohr ☝️ I note that for `skipEmpty` we actually support both text and HTML reports; might be a good next contribution for you?
CC: @coreyfarrell for review.
> feat: allow rows with 100% statement, branch, and function coverage to be skipped in text report

- README.md
The current documentation implies that ONLY the environment named `test` is valid for coverage reporting using Babel.  In fact, multiple environments can be used (and should be) if the tests require it.
> Update README.md with babel configuration info

- index.js
- lib/hash.js
- test/fixtures/identical-file-runner.js
- test/fixtures/identical-file1.js
- test/fixtures/identical-file2.js
- test/src/nyc-tap.js
When updating caching--transform it was missed that the `hash` option
has been refactored.  This means that two files with identical contents
would be treated as identical.
Add a test to verify that two sources with identical contents are
both instrumented.
> fix: Update caching-transform options.

- index.js
- lib/config-util.js
- lib/instrumenters/istanbul.js
- test/fixtures/cli/not-strict.js
- test/nyc-bin.js
nyc was hard-coded to use `esModules: true` when running the
instrumenter.  This could result in certain scripts not being
instrumented.
```js
function package() {
return 'package is a reserved keyword'
}
console.log(package())
```
Using `--es-modules false` will allow this script to be instrumented.
Issue #796
> fix: Add flag to allow instrumentation of non-strict scripts.

- lib/config-util.js
- test/nyc-bin.js
A previous fix for #796 added an es-modules option and set it false by
default.  This default was a change of behavior in NYC as previously all
sources were parsed as ES modules by the instrumenter.  I believe the
old behavior is the correct default because it allows NYC to work with
modern code.  Code which uses certain features which violate strict mode
will have to disable es-modules.  This will not effect ES5 which follows
the rules of 'use strict'.
> fix: Enable es-modules by default.

- README.md
- index.js
- lib/commands/merge.js
- lib/commands/report.js
- lib/config-util.js
- package.json
This change makes the option naming consistent using the form --*-dir, fixes #895 
Deprecates the option name --temp-directory in favour of --temp-dir.  --temp-directory has been demoted to a yargs alias of --temp-dir, so it will still work with existing projects.  I've updated the docs and changed the package.json test scripts to use the newer form.
I'm a little unsure of how tests should work for this, I've modified the package.json tests to use the new form, but then that doesn't test that the deprecated form still works, thoughts?
> Rename --temp-directory option to --temp-dir

- README.md
It's not `@babel/env`, it's `@babel/preset-env`
> [docs] @babel/env should be @babel/preset-env

- package-lock.json
- package.json
- test/src/nyc-tap.js
This causes an update to mem to resolve a potential DoS vulnerability in
command-line processing.
The vulnerable version of mem is still included by development
dependencies.
Fixes #918
> chore: Update dependencies.

- bin/nyc.js
By default, spawn-wrap writes temporary files to HOME.
It used to be /tmp, but it changed that to HOME to support
environments that have 'noexec' flags set on their tmpfs mount.
Ref https://github.com/tapjs/spawn-wrap/issues/3.
The problem with this is that nyc now no longer works in environments
without a (writable) home directory (e.g. the 'nobody' user on
Linux).
While it is fine to fallback to HOME, it should write elsewhere
if that is unavailable, and ideally in a way that doesn't require
every sysadmin or end-user to hardcode some environment variable
in their package.json specifically for nyc or spawn-wrap.
A common way to communicate this intent is with the XDG_CACHE_HOME
environment variable.
Fixes #951.
> feat: avoid hardcoded HOME for spawn-wrap working dir

- README.md
- lib/config-util.js
- test/nyc-bin.js
Since https://github.com/istanbuljs/nyc/pull/454, caching has been enabled by default but the README does not reflect this. Our team lost some time following the README, so contributing back our findings for the next team!
> Make update to caching information in readme

- index.js
- lib/instrumenters/istanbul.js
This PR introduces:
The ability to add more plugins for [@babel/parser](https://babeljs.io/docs/en/babel-parser) to istanbuljs instrumenter
related https://github.com/poetapp/node/pull/230 https://github.com/istanbuljs/istanbuljs/pull/205
> feat: Option Plugins

- lib/instrumenters/istanbul.js
- lib/instrumenters/noop.js
**Take advantage of features available in node.js 6 and above**
* Remove unreachable code for importing legacy `istanbul` module.
* Use `const` where possible
* Use object destructuring where appropriate.
* Use short-hand function declarations
> Modernize lib/instrumenters.

- index.js
- package-lock.json
- package.json
Add support to exclude files on coverage report generation (https://github.com/istanbuljs/istanbuljs/pull/275) to `nyc` (https://github.com/istanbuljs/nyc/issues/956).
> Add support to exclude files on coverage report generation

- .gitignore
- index.js
- package-lock.json
- package.json
- test/fixtures/cli/include-exclude/exclude-negated.js
- test/fixtures/cli/include-exclude/excluded.js
- test/fixtures/cli/include-exclude/node_modules/cover-me.js
- test/nyc-bin.js
Reverts istanbuljs/nyc#977
---
@AndrewFinlay we need to revert for now.  After istanbuljs/istanbuljs#307 is merged we should be able to make this happen from the `test-exclude` side.
> Revert "fix: Exclude negated not working with '--all' switch"

- index.js
- lib/hash.js
This PR adds the instrumenter-related config options to the salt of the cache hash. This fixes a bug where code that has been cached without instrumentation or source maps is incorrectly reused after the options are later enabled, leading to missing instrumentation. This problem is more likely to come up in projects using `babel-plugin-istanbul` which recommends setting the `sourceMap` and `instrument` options to `false`.
Closes #552 and probably also #822 #822 #974 #980
Thank you to everyone maintaining and contributing to this project :heart:
> fix: add config values to hash salt

- lib/commands/instrument.js
- test/nyc-integration.js
This is pretty straightforward, allow the es-modules option to flow through to the instrumenter when running the standalone instrument command.
Tests adapted from the existing tests for the regular es-modules command.
> feat: add `es-modules` option to instrument command

- test/nyc-integration.js
CI runs between #1012 and #1006 got crossed.
> chore: Fix es-module test to check for absolute file path in error.

- index.js
- lib/commands/check-coverage.js
- lib/commands/report.js
- package-lock.json
- package.json
- test/nyc-integration.js
I'm not sure if this qualifies as a feature or a fix, filtering after remapping has never worked.  Original implementation of filtering remapped sources at dd40dc51, addition of excludeAfterRemap option at cdfdff36.  Unfortunately the filtering step was done before coverage was remapped using source-maps, so it didn't do anything.
This is a potentially breaking change - bundled / compiled code was never filtered based on the original source filename, after this it will be.  As an auxiliary change `test-exclude` options are also added to the `nyc report` and `nyc check-coverage` as those commands should process exclude-after-remap.
Fixes #956
> feat: Fix excludeAfterRemap functionality.

- index.js
- lib/commands/instrument.js
- test/nyc-integration.js
This is an attempt to use some more modern language features in the `instrument.js` and the `instrumentAllFiles` command.  It's a cut back version of what I was proposing in #1003 as per conversation with @coreyfarrell.
As there's quite a bit here I'll drop in some notes and assumptions
* Notes:
1. Refactor `nyc-integration` instrument tests so tests with output folder specified aren't in the no output folder suite
2. Refactor `instrument.js` and `instrumentAllFiles` command to use modern javascript
3. Remove call to deprecated `process.exit()` in instrument command
4. Removed unused transform metadata param `relFile`, _this is an issue in other parts of the code_.
5. Use file extension as an index to find the correct transform, rather than trying to match a transform name to the …
> chore: update instrument code to use es2015+

- index.js
- lib/config-util.js
- test/nyc-integration.js
This allows a user to build the processinfo temp files, without actually
dumping the process tree to stdout.
The goal is to use this in node-tap to see which processes covered which
files, so we know which tests to re-run on changes to the source files.
> feat: add `--build-process-tree` feature

- index.js
- lib/hash.js
- lib/instrumenters/istanbul.js
The original option name created confusion about what was expected.
This helps identify that babel parser plugins are expected, not babel
transform plugins.
BREAKING CHANGE: The `plugins` option has been renamed to
`parser-plugins`.
Fixes #986
> feat: Rename `plugins` option to `parser-plugins`.

- index.js
- lib/commands/instrument.js
- lib/instrumenters/istanbul.js
A few code cleanups that I bumped into over the last few days.  I've tried to keep these changes as basic as possible, that being said please take a closer look at the `addFile` and `createInstrumenter` changes, in both cases I'm assuming that what I'm removing is dead code.
> chore: A few code cleanups

- README.md
So I got a little off track while trying to add `instrument --cwd`, so I figured I'd spend some time understanding what it does, opposed to what I think it should do, and put some documentation together in the process.  I'm still not 100% sure this is correct, it's my reading of the intention of the code.  A few notes, I haven't mentioned `env.NYC_CWD` as I figured that it's not really supposed to be directly accessed by users.  I also didn't mention that `cwd` is fed in while creating a new instrumenter, as it looks to be ignored.
> docs: project root directory and `--cwd` doc

- README.md
These are things that I didn't like in my original docs, the final straw being finding 'in in' in one of the lines.  Hopefully this makes things better!
Note I also added a change to the list of default `.nycrc` files to include `nyc.config.js`
> docs: a bunch of updates to recent docs

- lib/source-maps.js
- test/source-maps.js
during normal operation nyc will instantiate SourceMaps multiple times:
* once during initial instrumentation/execution step.
* once when reporting takes place.
Because `--all`  does not save source-maps to cache (as is the case when files are loaded during normal execution) the source-maps extracted by `--all` are dropped on the floor and never used.
This tiny fix makes source-maps start working in conjunction with `--all`.
> fix: make --all work for transpiled code

- bin/nyc.js
This shares the same instance of nyc for execution, checking coverage
and reporting.
> fix: Use a single instance of nyc for all actions of main command.

- bin/wrap.js
- test/nyc-integration.js
As of Node.js v6, process.ppid is available, and a number.  So, there's
no need to pass the parent PID through the environment, which casts it
to a string.
> fix: set processinfo pid/ppid to actual numbers

- bin/nyc.js
- bin/wrap.js
- index.js
- lib/process.js
- test/processinfo.js
THIS IS A WIP COMMIT FOR REVIEW ONLY, DO NOT MERGE
---
feat: add processinfo index, add externalId
If a NYC_PROCESSINFO_EXTERNAL_ID environment variable is set, then it is
saved in the processinfo as `externalId`.
BREAKING CHANGE: This adds a file named 'index.json' to the
.nyc_output/processinfo directory, which has a different format from the
other files in this dir.
Furthermore, when this file is generated, some additional helpful
metadata is memoized to the processinfo json files, to minimize the cost
of repeated generation.  (This isn't necessarily a breaking change, but
it is an update to the de facto schema for those files.)
As soon as possible, index generation and process tree display should be
migrated out to a new 'istanbul-lib-processinfo' library.
This opens the door to add …
> feat: add processinfo index, add externalId

- bin/nyc.js
- index.js
- lib/config-util.js
- test/nyc-integration.js
- test/processinfo.js
Always build the processinfo data directory (with index) in
${tmpdir}/processinfo.  This more easily supports cases where the
processinfo index may be useful for later analysis, or generating the
process tree post hoc.
BREAKING CHANGE: this removes the --build-process-tree option, which
appeared in previous 14.0.0 prerelease versions.
> feat: always build the processinfo temp dir

- README.md
Lists basic usage, with a key limitation that the input dir must equal or be a sub-dir of cwd.
I'll probably make a few changes tomorrow, so suggestions are welcome.
> docs: `nyc instrument` and `--exclude-node-modules`

- index.js
This PR intentionally avoids all auxiliary changes, this is a pure conversion from prototype based object to class based object.  If you download and view with `git diff HEAD~1 --ignore-all-space` the patch is 90% smaller (only adds/deletes 45 lines).
One change of code `nyc.generateUniqueID()` no longer exists.  This was only used by the constructor which now just calls `uuid()` directly.  `coverageFinder` is moved from the middle of the file to the top but is otherwise unchanged.  I did it this way as I didn't want to mix relevant changes with a formatting change effecting 90% of index.js.
> chore: Use class to declare NYC

- bin/nyc.js
- test/nyc-integration.js
When nyc is not told to do anything this is an error.  We already
printed the help message to stderr, now we exit with code 1 to indicate
that nyc exited without doing anything.
Add a test to cover this edge case and verify that both `nyc` and `nyc
--help` produce output as expected to stdout and stderr, exit with the
proper code.
> fix: Exit with code 1 when nyc doesn't know what to do.

- test/fixtures/cli/by-arg2.js
- test/nyc-integration.js
Verify that running `nyc command1 && nyc --no-clean command2` causes
results results to be merged.
> chore: Add test for `nyc --no-clean`.

- README.md
- docs/instrument.md
Add documentation for `--complete-copy`, and describe how to instrument source JIT on an express server.
This should go some way to addressing #839, which looks like it's already implemented but not documented.
> docs: instrument docs update

- package.json
- tap-snapshots/test-nyc-integration.js-TAP.test.js
- test/nyc-integration.js
node.js 12 changes the format of `util.inspect`, this causes snapshot
mismatch.  We only use object snapshot testing in one place so call
`util.inspect` manually with `compact: false` option to force consistent
output before / after node.js 12.
---
CC @isaacs not sure if tap@12 can/should do anything about this, kind of a tough situation as `compact: false` would be a breaking change for tap.  Either way figure you might want to know about this.
> chore: node.js 12 compatibility for object snapshot test.

- .github/ISSUE_TEMPLATE.md
- README.md
The intent here is to make the readme much better for newcomers and getting started faster. The major change is promoting the config packages and moving the more advanced features and options towards the bottom. Let me know what you think!
Fixes ...many issues. Hopefully.
Resolves ...many questions. Hopefully.
Easier diff to read: https://github.com/istanbuljs/nyc/tree/82a6dd5
> Readme Reshuffle

- tap-snapshots/test-nyc-integration.js-TAP.test.js
- test/nyc-integration.js
The new version of tap sorts the snapshots, regenerate and allow
`npm run snap` to run in parallel.
> chore: Regenerate snapshots for tap >= 12.6.3

- README.md
Image is no longer insecure when viewing REAMDE off of github (which does not serve the original image URLs).  Previously, the insecure content warning would show on npm when viewing the [nyc package](https://www.npmjs.com/package/nyc).
> Fix Slack badge image insecure content warning

- lib/commands/check-coverage.js
- lib/commands/instrument.js
- lib/commands/merge.js
- lib/commands/report.js
- tap-snapshots/test-nyc-integration.js-TAP.test.js
- test/nyc-integration.js
This applies to check-coverage, instrument, merge and report.  Passing
additional arguments will now cause the help script to be displayed and
an error exit code.
Unknown flags `nyc report --unknown=1` are still not reported.
Reporting unknown flags would require additional work as
`yargs.strict()` causes unknown items from configuration to be reported,
including flags that are defined for the global command but not a
sub-command.
Fixes #401
---
Is this a breaking change?  I lean towards no but can see the argument.  Likely this will first be released to 15.0.0 anyways but I'm not sure if it should be noted under breaking changes in the changelog.
> fix(cli): Report error if unwanted positional arguments are received

- bin/nyc.js
- bin/wrap.js
- index.js
- lib/process.js
- test/processinfo.js
This removes the NYC_ROOT_ID and NYC_INSTRUMENTER environment variables, which are no longer used or necessary.
Probably best to leave NYC_CWD in place, since it's more load-bearing, and is sometimes inspected in user code to determine whether or not they're being covered by NYC.
> chore: remove vestigial environment variables

- README.md
- lib/commands/instrument.js
- lib/commands/report.js
- lib/config-util.js
Fixes #1103
---
I don't want to pull TypeScript into the devDependencies so I'm not sure if this is going to get testing.  Maybe we could put regular JS into files of these extensions?
The fact that `extension` was missing from the `nyc report` command is minor - only effected the `nyc report --help` output.  Now that the default is non-empty it will matter.  I'd like to look into creating groups of flags - for example a shared function which adds all flags that apply to `test-exclude`.  That is not part of this.
> feat: Add `.cjs`, `.mjs`, `.ts`, `.tsx`, `.jsx` to default extensions

- package.json
If the tests fail with a bad 'test/fixtures/cli/foo-cache', then subsequent tests will also fail unless the cache is cleaned.
A failed test run also leaves a lot of files in 'test/temp-dir-nyc-integration' that are cleaned on success, but not before the start of the next run in case of failure.
> chore: Remove test artefacts that can ensure failure on subsequent tests

- index.js
The callback is run but we're unable to record coverage for it.
> chore: Suppress coverage for onExit callback

- package-lock.json
- package.json
This would resolve #1151 to eliminate the npm vulnerability `Prototype Pollution` identified by https://www.npmjs.com/advisories/1065.
> Upgrade lodash to ^4.17.15 to eliminate vulnerability

- docs/instrument.md
- lib/commands/instrument.js
- tap-snapshots/test-nyc-integration.js-TAP.test.js
- test/fixtures/cli/instrument-inplace/file1.js
- test/fixtures/cli/instrument-inplace/file2.js
- test/nyc-integration-old.js
This PR addresses #1135
This change adds the `--in-place` switch to nyc instrument
If `--in-place` is specified, the output directory will be set to equal the input directory for the instrument command.
This has the effect of replacing any file in the input directory that should be instrumented, with its instrumented counterpart.
The command will throw an error if the --delete option is specified.
The only way to instrument in place is with the --in-place switch, setting the input and output directories to be the same will not work
If `--in-place` is set the instrument command ignores any output directory specified with the command
If `--in-place` is set the instrument command will disable the `--complete-copy` switch as it is unnecessary.
I've made a few small code improvements to the …
> feat: Allow `nyc instrument` to instrument code in place

- index.js
- lib/instrumenters/noop.js
Sometimes the coverage data produced by `nyc --all` is incompatible with
the coverage data produced by actual test runs.  This is generally due
to configuration error but results in inconsistent coverage reports or
in some cases causes `nyc report` to crash.  The workaround is
implemented in istanbul-lib-coverage to drop coverage data associated
with `nyc --all` when coverage data from a test run is found.  This
commit tags the coverage data when appropriate so the coverage merge
logic knows what to do.
Fixes #1113, #1124, #1148
> fix: Drop coverage produced by `nyc --all` for files that were tested

- index.js
- lib/source-maps.js
- tap-snapshots/test-nyc-integration.js-TAP.test.js
- test/nyc-integration.js
This utilizes a new feature of caching-transform@4 to prefix cache instrumented sources and source-maps with a more useful name.  For example `lib/worker.js` might get cached as `node_modules/.cache/nyc/worker-d84d3c7a86d2657c33e0c6f4fe3013270d7887ae76e3bf14bde6286cffc79b47.js`.  Also added a test to verify creation of the cached source map when appropriate.
> feat: Use source base name to prefix cache files

- .github/stale.yml
The default delay for the stale bot is too aggressive for our ability to
keep up with issues.  This changes from 60 days to 365 days.
> chore: Longer delay for stale bot

- lib/source-maps.js
* Convert to class
* Prefer const over var
* Use Object.entries()
---
This eliminates the last use of prototype based class declaration in nyc, `git grep prototype` only shows the one place where a test replaces one of the nyc methods.
> chore: Modernize lib/source-maps.js

- npm-run-clean.js
- package.json
This allows use of globs without risk of shell interference, makes it
easier to read the list of delete targets.
---
Maybe `build-self-coverage.js` should be renamed to `npm-run-instrument.js` for consistent naming of `npm run` scripts?
> chore: Create npm-run-clean.js script

- lib/instrumenters/istanbul.js
- lib/instrumenters/noop.js
- tap-snapshots/test-eager.js-TAP.test.js
- test/eager.js
- test/fixtures/eager.js
This delays loading of istanbul-lib-instrument until it is needed.
---
This fixes a performance regression caused by #985, adds tests to prevent in the future.  To test you can create a script `eager.js`:
```js
console.log(Object.keys(require.cache).length - 1); // don't count eager.js itself
```
Then you can test the effect of non-eager loading:
```
$ node eager.js
0
$ ./bin/nyc.js --silent --exclude=eager.js --eager=true node eager.js
293
$ ./bin/nyc.js --silent --exclude=eager.js node eager.js
143
```
Running under nyc with `eager: true` (or without this patch) results in 293 additional modules being loaded, this patch by default reduces the "always load" to 143.  This is demonstrated here by ensuring that all sources are excluded from instrument but in practice large test suites that …
> fix: Honor eager setting (false by default)

- package-lock.json
- package.json
- test/instrument.js
- test/source-map-support.js
FWIW the issue in test/source-map-support.js existed before these updates, it's just now exposed.  Previously the wrong line of the stack-trace was listing line 4, now it's not.  Oddly enough the throw from line 4 of `fixtures/stack-trace.js` is being listed as line 3 (this is unchanged).
> chore: Update dependencies

- index.js
- self-coverage-helper.js
This allows us to record coverage for all code called from the
signal-exit handler.
> chore: Coverage for signal-exit handler.

- index.js
- lib/source-maps.js
Prior to this change child processes would call upon the source-map
module to remap coverage during the `signal-exit` handler.  This was a
blocker for updating `source-map` to 0.7.x which uses an async
constructor method.
Now we simply save the source-map with the raw coverage data for each
file.  This allows the main nyc process to perform source-map remapping.
The benefit is that the main nyc process can use async code.
> fix: Avoid `source-map` module during `signal-exit` handler

- bin/nyc.js
- index.js
- lib/commands/check-coverage.js
- lib/commands/cli-wrapper.js
- lib/commands/instrument.js
- lib/commands/merge.js
- lib/commands/report.js
- lib/fs-promises.js
- lib/source-maps.js
- package-lock.json
- package.json
- tap-snapshots/test-nyc-integration.js-TAP.test.js
- test/add-all-files.js
- test/cache.js
- test/instrument.js
- test/issue-190.js
- test/nyc-integration.js
- test/processinfo.js
- test/report.js
- test/source-map-support.js
- test/temp-dir.js
- test/wrap.js
Might be missing a couple places but I wanted to be careful to avoid stuff that is used by the `signal-exit` callback.
> chore: Use async functions where reasonable

- bin/nyc.js
nyc.addAllFiles needs to be called after the `!argv.useSpawnWrap` branch
performs the `require`'s and we need to await it.
> chore: Fix merge error

- index.js
This allows istanbul-lib-processinfo to read coverage data files using
only the `coverageFileLoad` function.
> chore: Tweak arguments for async coverage data readers

- package.json
This causes confusion among users who think they're reading about the
latest releaase.  It is better that we send users to istanbul.js.org for
documentation.
Issue #1200
---
@bcoe another option would be to use https://npmjs.com/packages/nyc as the homepage.  I'm fine with either one.
> docs: `npm home nyc` goes to github master branch README

- index.js
- lib/source-maps.js
A couple of sync functions were left behind for a previous version of
istanbul-lib-processinfo.  These functions are no longer used so they
are removed.
> chore: Remove unused functions

- README.md
default-exclude list has moved, missed a link in #1214.
Fixes #1219
> chore: Fix 404 in README.md.

- index.js
- package-lock.json
- package.json
- test/instrument.js
This slightly reduces the amount of code nyc loads by using the core
fs.copyFile function.  Clarify `package.json#engines` to show that
node.js 8.9.0 (LTS) is the oldest supported release.
> chore: Remove cp-file module

- index.js
This reduces `Object.keys(require.cache).length` in child processes by a couple dozen.  This reduction in loaded modules could add up for repositories which use hundreds or even thousands of child processes.
> chore: Lazy load modules that are rarely/never needed in test processes.

- index.js
Add the possibility to use --relative=true option in command line
This is useful if you run your test on a linux environment (docker, vm, server) and dev on a windows one.
If you want your coverage to work with your IDE, you need relative path instead of absolute ones.
Linked with pull request https://github.com/istanbuljs/istanbuljs/pull/492
> Add support for relative path option

- package.json
It seems this is now moved to @istanbuljs/load-nyc-config
> (chore) Remove the unused js-yaml dependency.

- package.json
This seems to be included in istanbul-lib-processinfo, but please confirm.
> (chore) Remove the unused uuid dependency

- test/helpers/run-nyc.js
Fixes test failures on Windows.
Fixes #1248 
@coreyfarrell I used your author info, feel free to tweak the commit message when merging.
> (fix) Conditionally set `envPath.APPDATA`

- .travis.yml
- README.md
- appveyor.yml
@coreyfarrell the only changes you should make in AppVeyor settings are these:
* Skip branches without appveyor.yml
* Save build cache in Pull Requests
Notes:
> (chore) Switch to AppVeyor for Windows testing

- package-lock.json
- package.json
It's my understanding that v0.2.1 has some important fixes.
> (chore) Update node-preload to v0.2.1

- README.md
Updated some of the text to make support the changes to the config examples.
Updated the doc for the `ignore-class-method` example to try and reflect that it accepts an array of strings, rather than just a single string.
> docs: Remove `nyc` containing object in json config examples

- test/nyc-integration.js
This change allows for flaky output of help information from `yargs` to `stderr` when running `nyc` as a child process.
Fixes #1259.
> fix: A test where nyc output help text to stderr was flaky

- .gitignore
- index.js
This PR fixes https://github.com/istanbuljs/nyc/issues/1263
Instead of fetching all reports into memory and then merging, we do that one-by-one.
> Data merge concurrency

- package-lock.json
- package.json
- test/source-map-support.js
Still a couple audit warnings coming via deep deps of standard-version.
> chore: Regenerate package-lock, update source-map-support test

- index.js
- package-lock.json
- package.json
- tap-snapshots/test-nyc-integration.js-TAP.test.js
- test/fixtures/all-type-module/extra.mjs
- test/fixtures/all-type-module/index.js
- test/fixtures/all-type-module/package.json
- test/fixtures/all-type-module/script.cjs
- test/nyc-integration.js
This allows `--all` to collect initial coverage from fils which node.js
recognizes as ES modules (`.mjs` files and conditionally `.js` files).
Previously this would cause node.js to produce an `ERR_REQUIRE_ESM`
error.
This does not enable collection of coverage during actual tests, for that
you must use the experimental `@istanbuljs/esm-loader-hook`.
> feat(experimental): Support using `--all` with node.js ES modules

- .taprc
- index.js
- package.json
- self-coverage-helper.js
This avoids the conditional `require('../self-coverage-helper')` which
can create difficulty for code analysis.  Also use uuid v4 to generate
self coverage filenames instead of process.pid.
> chore: Tweak self-coverage implementation

- README.md
Awasome project! thanks.
That said, I came to this project because IntelliJ suggested me to use it in order to execute mocha tests with code coverage, so like any developer, before accept the IntelliJ suggestion I went to the official Npm section to see what is this package about, and like here in the Github README, you can see a lot of links and information but not what `ncy` actually does, so I just copy&pasted the introductory section from the official site.
> Add introductory section to README

- lib/commands/merge.js
Fixes https://github.com/istanbuljs/nyc/issues/1451
`null, 2` pretty prints the json but this adds so much white space we hit the node limitation in string sizes https://github.com/nodejs/node/issues/35973#issuecomment-722253319
> fix `nyc merge` stringify hitting Invalid string length
